### ISSUE TITLE
help request:  problems paying for storage on poly mumbai testnet

### ISSUE THREAD

**Issue by srblabotw69** [filswan/js-mcs-sdk#6]
Hi,

I have been having difficulties recently with paying for storage on the testnet even though I believe I have enough funds in wallet. 
Below is the error and file details (uploaded to IPFS already).  Status appears to be always "pending".  Please advise.  Thanks.

I have the following fund in test wallet:

0.0968
MATIC

197
USDC

ERROR
=================

/node_modules/web3-core-helpers/lib/errors.js:28
        var err = new Error('Returned error: ' + message);
                  ^

Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (../node_modules/web3-core-helpers/lib/errors.js:28:19)
    at ../node_modules/web3-core-requestmanager/lib/index.js:300:36
    at ../node_modules/web3-providers-http/lib/index.js:124:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: null
}

UPLOAD FILE DETAILS
=================

// [
//   {
//     status: 'success',
//     data: {
//       source_file_upload_id: 476742,
//       payload_cid: 'Qmerw1LjXrcm52y6RoTSmFiZHuHqWKzJ5b8dzpkoofuELf',
//       ipfs_url: 'https://calibration-ipfs.filswan.com/ipfs/Qmerw1LjXrcm52y6RoTSmFiZHuHqWKzJ5b8dzpkoofuELf',
//       file_size: 19,
//       w_cid: '8a1c9f2d-853d-49b2-a87b-299fb21f5d92Qmerw1LjXrcm52y6RoTSmFiZHuHqWKzJ5b8dzpkoofuELf'
//     }
//   }
// ]

/ [
//   {
//     source_file_upload_id: 476742,
//     car_file_id: 0,
//     file_name: 'JnK0N.txt',
//     file_size: 19,
//     upload_at: 1659664087,
//     duration: 525,
//     ipfs_url: 'https://calibration-ipfs.filswan.com/ipfs/Qmerw1LjXrcm52y6RoTSmFiZHuHqWKzJ5b8dzpkoofuELf',
//     pin_status: 'Pinned',
//     payload_cid: '',
//     w_cid: '8a1c9f2d-853d-49b2-a87b-299fb21f5d92Qmerw1LjXrcm52y6RoTSmFiZHuHqWKzJ5b8dzpkoofuELf',
//     status: 'Pending',
//     deal_success: false,
//     is_minted: false,
//     token_id: null,
//     mint_address: null,
//     nft_tx_hash: null,
//     offline_deal: []
//   },

**Comment by flyworker** [comment]
mumai testnet currently experience high gas fee, suggest you to have 0/5~1 matic in your wallet
